INDICATOR_MACD = "macd"
INDICATOR_RSI = "rsi"
INDICATOR_STOCHASTIC = "stochastic"
INDICATOR_STOCHASTIC_RSI = "stochrsi"

INDICATOR_TYPES = [
            INDICATOR_MACD,
            INDICATOR_RSI,
            INDICATOR_STOCHASTIC,
            INDICATOR_STOCHASTIC_RSI,
        ]

INDONESIAN_INDEX = "JK"