# Generated by Django 2.1.4 on 2018-12-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('macd', 'macd'), ('rsi', 'rsi'), ('stochastic', 'stochastic')], default='macd', max_length=128)),
                ('value', models.DecimalField(decimal_places=3, max_digits=99)),
                ('stock_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='stock_app.Company')),
            ],
        ),
    ]
