# Generated by Django 2.1.4 on 2018-12-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_auto_20181206_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalindicator',
            old_name='stock_code',
            new_name='company',
        ),
    ]
